import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cookies } from 'next/headers'
import { DarkToggle } from './components/dark-mode'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const savedTheme = cookies().get('theme-color')
	const preferenceTheme = cookies().get('theme-preference')

	const theme = savedTheme?.value || preferenceTheme?.value || 'light'

	return (
		<html lang="en" data-theme-color={theme}>
			<body className={inter.className}>
				<header className="header">
					<DarkToggle initialTheme={theme} />
				</header>
				{children}
			</body>
		</html>
	)
}
