import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import { ThemeToggle } from './components/theme-toggle'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const ThemeScript = () => {
	const codeToRunOnClient = `
		(function() {
			if(document.documentElement.getAttribute('data-theme-preference') === 'system' && window.matchMedia) {
				const theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
				document.documentElement.setAttribute('data-theme-color', theme)

				window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', event => {
					const newColorScheme = event.matches ? "dark" : "light";
					document.documentElement.setAttribute('data-theme-color', newColorScheme)
			});
			}
		})()
	`

	return <script dangerouslySetInnerHTML={{ __html: codeToRunOnClient }} />
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const savedTheme = cookies().get('theme-color')
	const theme = savedTheme?.value || 'system'

	return (
		<html lang="en" data-theme-color={theme} data-theme-preference={theme}>
			<head>
				<ThemeScript />
			</head>
			<body className={inter.className}>
				<header className="header">
					<ThemeToggle initialTheme={theme} />
				</header>
				{children}
			</body>
		</html>
	)
}
